// export const ActionTypes = {
//   FETCH_PRODUCT: "FETCH_PRODUCT",
//   SET_PRODUCT : 'SET_PRODUCT',
//   SELECTED_PRODUCT :'SELECTED_PRODUCT',
//   REMOVE_SELECTED_PRODUCT :'REMOVE_SELECTED_PRODUCT'
// }
export const ActionTypes = {
  ADD_TO_CARD: "ADD_TO_CARD",
  
  REMOVE_TO_CARD :'REMOVE_TO_CARD'
} 